"""Compatibility facade for legacy imports from ``review_ops``.

The implementation now lives in ``ops.review`` with smaller modules for
XML primitives, comments and tracked revisions.
"""

from ops.package_io import read_zip_xml, serialize_xml
from ops.review import (
    REVISION_NAMESPACES,
    REVISION_XPATH,
    add_comment_node,
    anchor_comment_to_paragraph,
    anchor_comment_to_range,
    append_revision_pair,
    child_plain_text,
    clear_paragraph_content,
    comment_reference_run,
    comment_to_dict,
    convert_del_text_to_text,
    enable_track_revisions_part,
    ensure_comments_parts,
    find_text_range_xml,
    iter_document_paragraphs_xml,
    iter_document_tables_xml,
    list_comments_xml,
    list_revisions_xml,
    new_text_run,
    new_w_element,
    next_comment_id,
    next_revision_id,
    paragraph_revision_view,
    paragraph_text_xml,
    replace_in_paragraph_tracked,
    revision_details_xml,
    revision_text,
    revision_to_dict,
    settings_has_track_revisions,
    unwrap_revision,
    w_attr,
    xml_space_attr,
)

__all__ = [
    "REVISION_NAMESPACES",
    "REVISION_XPATH",
    "add_comment_node",
    "anchor_comment_to_paragraph",
    "anchor_comment_to_range",
    "append_revision_pair",
    "child_plain_text",
    "clear_paragraph_content",
    "comment_reference_run",
    "comment_to_dict",
    "convert_del_text_to_text",
    "enable_track_revisions_part",
    "ensure_comments_parts",
    "find_text_range_xml",
    "iter_document_paragraphs_xml",
    "iter_document_tables_xml",
    "list_comments_xml",
    "list_revisions_xml",
    "new_text_run",
    "new_w_element",
    "next_comment_id",
    "next_revision_id",
    "paragraph_revision_view",
    "paragraph_text_xml",
    "read_zip_xml",
    "replace_in_paragraph_tracked",
    "revision_details_xml",
    "revision_text",
    "revision_to_dict",
    "serialize_xml",
    "settings_has_track_revisions",
    "unwrap_revision",
    "w_attr",
    "xml_space_attr",
]


